language: generic
dist: xenial
sudo: required

before_script: 
- scripts/provision.sh
- sudo busybox httpd -f &

script:
- inspec exec tests/default

before_deploy:
  - mkdir www && cp index.html www/.

deploy:

  - provider: s3
    access_key_id:
      secure: "Sm/zYOBHY9E5nGBDr681tvlPAdelT/AuPUFlqVSUsV7VO7gm+XTk3JKIpMIaWdb9be+CwHT0pJu9t+XAARblw1YesSP49nsK+/yvjNEz58wSxpZNiNaflM2ugEoSsjeZMU/v7xZWn9BvL3DppGggxiu+2RiRTlhE4jfqjsw9iaxV6GEsFFQkJ8tedxiUgzZhk5HcYOH/Cv9vZEY80qSHW+4sE4iJJ5X9VWUb1Odzq1Q32oMfxy37Xr7qs8ZZrMGjVO303FnUHVcaiZq+R8OgadJh8bkEO7KRwhN7cEFaHCxJe+kiOxe4N4gnDYp5v/yGw5oD6YWb7xLP5/SSNyLNfJaUIgpFamOGixaAmAo59EMA/PNMebEcPPCvTYSKuU4PVU2+wts9kPeZ3aMZUmGsSeFAPE0U9km//DhWQxSrKv1dIH7KSeMRBQevF98JkW/ZvhFxkKhST2flkGAI4N/o6WopH1rgkvtsCXgArPvDVIQV3tv2s2Un4/u8EdIA62nIDIZmW3lARZcpVBckKYQHSCpGYyO7gw9wFgK9FjiR/GkFI+xJBmpqHVgUbunoYGV22KfIXevK5sOBRl4HjIyxR/+Z7Fo91ozgSNl1LZaXCJMMbbVKk83T8SSg5rpdoj6NbuNRg27sQ4AIRZGMx3fg+tBoNewRVMSBPBgjM5BhUc4="
    secret_access_key:
      secure: "A0LFUy0lJhZLXBjp2/fvH+CdhXzc7JE2MWcodxnlS+wZRVDiJ5+G6voSf+FG4pVY5WUePauPu/nCnR7nJ/5ShamgtijshZWLpNLyika4uYzrrBV3U+Pemaym9u3PvLtJMMIqyalgQB9eiqv5f+4eFTtoZehCs9KRqBISXxp3T/POUNJfbYGco6adcUjZbR6qJXLqf/dorPyUX366bsC9Jd8GoN+pqpG7dj0Yso7tbgAXzwgscqMEVcU4lwSPeLfwsNmzVAQNbd+LR+xxCtEgy3krI0SW4Fr8tdRIbvNnAbHHbPRTc2qBbByeMZp/Ki2my3WJ/Y+42joIuBgr+Uqjvglb4sXvffLx1x7M+iAFGgMs12zsk9vcjDpd37o84Ss4J0Tuu0Prj6b7cdCI8mT2aghLdG1G9wiNeiiprqfg5NTLO5pENXRYCHUi2L3Bamo+hZgirDRWnGHTLYVvS2hPKTPRKFuqpkRkPgk6Mq5dzrJO3HAmmPi4hmseVHZFGO5VMFZ3x+ZMV+GVriGEBjcrM5YiCaqHRns1LHa0MM3x0r/mKIrUFO15c34TV1b5DWWM0fcWGN9VafYZ2Je4frwa6Jq2LGxbCJYbWKCXIxgSFnRS5VKM3P/piWMUcak9Nr0iu7hldh9uxaZJjBdjj5tAF51Y1w2EEnw8Hab41xvhjcE="
    bucket: tf-cicd-demo-st
    skip_cleanup: true
    region: eu-central-1
    local_dir: www
    on:
      tags: false
      condition: "$TRAVIS_BRANCH =~ ^master$"

  - provider: s3
    access_key_id:
      secure: "Sm/zYOBHY9E5nGBDr681tvlPAdelT/AuPUFlqVSUsV7VO7gm+XTk3JKIpMIaWdb9be+CwHT0pJu9t+XAARblw1YesSP49nsK+/yvjNEz58wSxpZNiNaflM2ugEoSsjeZMU/v7xZWn9BvL3DppGggxiu+2RiRTlhE4jfqjsw9iaxV6GEsFFQkJ8tedxiUgzZhk5HcYOH/Cv9vZEY80qSHW+4sE4iJJ5X9VWUb1Odzq1Q32oMfxy37Xr7qs8ZZrMGjVO303FnUHVcaiZq+R8OgadJh8bkEO7KRwhN7cEFaHCxJe+kiOxe4N4gnDYp5v/yGw5oD6YWb7xLP5/SSNyLNfJaUIgpFamOGixaAmAo59EMA/PNMebEcPPCvTYSKuU4PVU2+wts9kPeZ3aMZUmGsSeFAPE0U9km//DhWQxSrKv1dIH7KSeMRBQevF98JkW/ZvhFxkKhST2flkGAI4N/o6WopH1rgkvtsCXgArPvDVIQV3tv2s2Un4/u8EdIA62nIDIZmW3lARZcpVBckKYQHSCpGYyO7gw9wFgK9FjiR/GkFI+xJBmpqHVgUbunoYGV22KfIXevK5sOBRl4HjIyxR/+Z7Fo91ozgSNl1LZaXCJMMbbVKk83T8SSg5rpdoj6NbuNRg27sQ4AIRZGMx3fg+tBoNewRVMSBPBgjM5BhUc4="
    secret_access_key:
      secure: "A0LFUy0lJhZLXBjp2/fvH+CdhXzc7JE2MWcodxnlS+wZRVDiJ5+G6voSf+FG4pVY5WUePauPu/nCnR7nJ/5ShamgtijshZWLpNLyika4uYzrrBV3U+Pemaym9u3PvLtJMMIqyalgQB9eiqv5f+4eFTtoZehCs9KRqBISXxp3T/POUNJfbYGco6adcUjZbR6qJXLqf/dorPyUX366bsC9Jd8GoN+pqpG7dj0Yso7tbgAXzwgscqMEVcU4lwSPeLfwsNmzVAQNbd+LR+xxCtEgy3krI0SW4Fr8tdRIbvNnAbHHbPRTc2qBbByeMZp/Ki2my3WJ/Y+42joIuBgr+Uqjvglb4sXvffLx1x7M+iAFGgMs12zsk9vcjDpd37o84Ss4J0Tuu0Prj6b7cdCI8mT2aghLdG1G9wiNeiiprqfg5NTLO5pENXRYCHUi2L3Bamo+hZgirDRWnGHTLYVvS2hPKTPRKFuqpkRkPgk6Mq5dzrJO3HAmmPi4hmseVHZFGO5VMFZ3x+ZMV+GVriGEBjcrM5YiCaqHRns1LHa0MM3x0r/mKIrUFO15c34TV1b5DWWM0fcWGN9VafYZ2Je4frwa6Jq2LGxbCJYbWKCXIxgSFnRS5VKM3P/piWMUcak9Nr0iu7hldh9uxaZJjBdjj5tAF51Y1w2EEnw8Hab41xvhjcE="
    bucket: tf-cicd-demo-prod
    skip_cleanup: true
    region: eu-central-1
    local_dir: www
    on:
      tags: true
